#!/bin/bash
# File is mainained in ~/.setup-mac/setup-mac


# Get Homebrew packet manager itself
BREW=/usr/local/bin/brew
if [ -e $BREW ]; then
   echo "* Homebrew is installed"
else
   echo "* Installing Homebrew ..."
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Get Homebrew command-line and graphical utilities (via cask)
HOMEBREW_MODULES="coreutils mercurial macvim sshpass"
HOMEBREW_CASKS="hyper fluor"

for module in $HOMEBREW_MODULES; do
   brew install $module
done

for cask_module in $HOMEBREW_CASKS; do
   brew cask install $cask_module
done

echo -e "* To customize Hyper, start it, select Plugins > 'Install Hyper CLI command in PATH'"
echo -e "* and then write (e.g.): 'hyper help'\n"

# Create gvim and pointer to _the_dir_this_file_is_in_ in $HOME
SETUP_MAC=$HOME/.setup-mac
VIM_DIR=$HOME/.vim

for dir in $SETUP_MAC $VIM_DIR $VIM_DIR/swap; do
    [ -e $dir ] || mkdir -vp $dir 
done

# Clone the vundle packet manager for gvim from github to the vim directory
if [ ! -e $VIM_DIR/bundle ]; then
   echo -e "* Downloading Vundle vi plugin manager to \$HOME/.vim/bundle\n"
   git clone https://github.com/VundleVim/Vundle.vim.git $VIM_DIR/bundle/Vundle.vim
fi

# Download github modules and link to homedir, if needed
[ -e $SETUP_MAC/dircolors-solarized ] || git clone https://github.com/seebi/dircolors-solarized $SETUP_MAC/dircolors-solarized
ln -sf $SETUP_MAC/dircolors-solarized/dircolors.ansi-light $HOME/.dir_colors

echo -e "* Install the IBM Plex Mono font from '$SETUP_MAC/plex'"
echo -e "* using the Mac's fontbook utility\n"
[ -e $SETUP_MAC/plex ]      || git clone https://github.com/IBM/plex $SETUP_MAC/plex

# Create links to files in this dir in $HOME
# Require access to geinov@noven.no mercurial repo
# If you have a zipped version, unzip it in ~/.mac_profile and comment out the next line
ln -sf $SETUP_MAC/bash_profile $HOME/.bash_profile
ln -sf $SETUP_MAC/vimrc $HOME/.vimrc
ln -sf $SETUP_MAC/gvimrc $HOME/.gvimrc
ln -sf $SETUP_MAC/gitconfig $HOME/.gitconfig
echo -e "* Open gvim and run :PluginInstall\n"
ln -sf $SETUP_MAC/hyper.js $HOME/.hyper.js
