#!/bin/zsh
# File is mainained in ~/.setup-mac/setup-mac
# Todo: include inputrc

# Accept the license of xcode
sudo xcodebuild -license accept

# Get Homebrew packet manager itself (assuming this install dir)
BREW=/opt/homebrew/bin/brew
if [ -e $BREW ]; then
   echo "* Homebrew is installed"
else
   echo "* Installing Homebrew ..."
   sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install the Oh My ZSH framework
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Get Homebrew command-line and graphical utilities (via cask)
HOMEBREW_MODULES="coreutils macvim gh figlet"
HOMEBREW_CASKS="hyper fluor"

for module in $( echo "$HOMEBREW_MODULES" )
do
   $BREW install $module
done

for cask_module in $( echo "$HOMEBREW_CASKS" )
do
   $BREW install --cask $cask_module
done

echo -e "* To customize Hyper, start it, select Plugins > 'Install Hyper CLI command in PATH'"
echo -e "* and then write (e.g.): 'hyper help'\n"

# Create gvim and pointer to _the_dir_this_file_is_in_ in $HOME
SETUP_MAC=$HOME/.setup-mac
VIM_DIR=$HOME/.vim

for dir in $SETUP_MAC $VIM_DIR $VIM_DIR/swap; do
    [ -e $dir ] || mkdir -vp $dir 
done

# Clone the vundle packet manager for gvim from github to the vim directory
if [ ! -e $VIM_DIR/bundle ]; then
   echo -e "* Downloading Vundle vi plugin manager to \$HOME/.vim/bundle\n"
   git clone https://github.com/VundleVim/Vundle.vim.git $VIM_DIR/bundle/Vundle.vim
fi

# Download github modules and link to homedir, if needed
[ -e $SETUP_MAC/dircolors-solarized ] || git clone https://github.com/seebi/dircolors-solarized $SETUP_MAC/dircolors-solarized
ln -sf $SETUP_MAC/dircolors-solarized/dircolors.ansi-light $HOME/.dir_colors

echo -e "* Install the IBM Plex Mono font from '$SETUP_MAC/plex'"
echo -e "* using the Mac's fontbook utility\n"
[ -e $SETUP_MAC/plex ]      || git clone https://github.com/IBM/plex $SETUP_MAC/plex

# Create links to files in this dir in $HOME
[ -e $HOME/.zshrc ] || ln -sf $SETUP_MAC/zshrc $HOME/.zshrc
[ -e $HOME/.vimrc ] || ln -sf $SETUP_MAC/vimrc $HOME/.vimrc
[ -e $HOME/.gvimrc ] || ln -sf $SETUP_MAC/gvimrc $HOME/.gvimrc
[ -e $HOME/.gitconfig ] || ln -sf $SETUP_MAC/gitconfig $HOME/.gitconfig
echo -e "* Open gvim and run :PluginInstall\n"
[ -e $HOME/.hyper.js ] || ln -sf $SETUP_MAC/hyper.js $HOME/.hyper.js


if [ -e $HOME/.zshrc ];then
if grep -iq "Added by setup-mac"  $HOME/.zshrc ; then
   echo "Sourcing of setup-mac/zshrc added before"
else
   echo "Added sourcing of setup-mac/zshrc"
   echo "source $HOME/.setup-mac/zshrc  # Added by setup-mac" >> $HOME/.zshrc
fi
fi
